Default: &defaults
  user: Joje
  password: Joje
  host: localhost
  port: 5432
  database: Joje
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Joje_test
  <<: *defaults

Staging:
  database: Joje_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Joje_production
  poolsize: 100
  <<: *defaults
